apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faaast-service.fullname" . }}-config
  labels:
    {{- include "faaast-service.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "persistence": {
        {{- if .Values.seeding.enabled }}
        "initialModelFile": "{{ .Values.seeding.mountPath }}/{{ .Values.seeding.filename }}",
        {{- end }}
        "@class": "{{ .Values.persistence.class }}",
        "connectionString": "{{ .Values.persistence.connectionString }}",
        "database": "{{ .Values.persistence.database }}",
        "override": "{{ .Values.persistence.override }}"
      },
      "messageBus": {
        "@class": "{{ .Values.messageBus.class }}",
        "host": "{{ .Values.messageBus.host }}",
        "user": "{{ .Values.messageBus.user }}",
        "password": "{{ .Values.messageBus.password }}",
        "slimEvents": "{{ .Values.messageBus.slimEvents }}",
        "eventCallbackAddress": "{{ .Values.messageBus.eventCallbackAddress }}"
      },
      "endpoints": [
        {
          "@class": "{{ (index .Values.endpoints 0).class }}",
          "port": {{ (index .Values.endpoints 0).port }},
          "corsEnabled": {{ (index .Values.endpoints 0).corsEnabled }},
          "sslEnabled": {{ (index .Values.endpoints 0).sslEnabled }}
        }
      ]
    }